export const importedBrandModels: Record<string, readonly string[]> = {
  "AB O. Mustad & Son": [
    "Mustad Folkscooter 111"
  ],
  "AJS": [
    "Model D"
  ],
  "Allen Millyard": [
    "Millyard Viper V10"
  ],
  "Apec": [
    "ALFA 125",
    "APX5 125",
    "PS3 50"
  ],
  "Aprilia": [
    "Area 51",
    "Atlantic",
    "Atlantic 200",
    "Atlantic 500",
    "Caponord",
    "Caponord 1200 ADD",
    "Caponord 1200 RALLY",
    "Dorsoduro",
    "Dorsoduro 750",
    "ETV 1000 Caponord",
    "Gulliver",
    "MANA 850",
    "Mille SP",
    "Mojito",
    "Mojito 150",
    "Mojito 50",
    "Pegaso 650",
    "Rally 50",
    "RS",
    "RS 457",
    "RS 660",
    "RS250",
    "RS4 125",
    "RS50",
    "RST Futura",
    "RSV 1000",
    "RSV 1000 R",
    "RSV Mille",
    "RSV Mille R",
    "RSV4",
    "RSV4 R",
    "RX",
    "RX 50",
    "RXV 450",
    "RXV 550",
    "RXV/SXV",
    "Scarabeo 100",
    "Scarabeo 150",
    "Scarabeo 200",
    "Scarabeo 250",
    "Scarabeo 50",
    "Scarabeo 500",
    "Shiver",
    "Shiver 750",
    "SL 1000",
    "Sport City 250",
    "Sportcity",
    "Sportcity One 125",
    "Sportcity One 50",
    "SR 50",
    "SRV 850",
    "SXR",
    "SXV 450",
    "SXV 550",
    "Tuareg",
    "Tuareg 660",
    "Tuono",
    "Tuono 1000",
    "Tuono 1000R",
    "Tuono 457",
    "Tuono 660",
    "Tuono V4",
    "Tuono V4 1100 Factory",
    "Tuono V4 1100 RR",
    "Tuono V4 R"
  ],
  "Ariel Motor Company": [
    "Ariel Ace"
  ],
  "Ariel Motorcycles": [
    "Ariel Leader"
  ],
  "Augustus Moore Herring": [
    "Herring"
  ],
  "Auto Union": [
    "DKW SB 500"
  ],
  "Bajaj": [
    "Acer",
    "Boxer",
    "Caliber",
    "Chetak",
    "Classic",
    "Eliminator",
    "Legend",
    "M80 Major",
    "Pulsar",
    "Saffire",
    "Spice",
    "Spirit",
    "Sunny"
  ],
  "Benelli": [
    "180",
    "302",
    "752",
    "900 Sei",
    "Adiva",
    "BN 125",
    "BN 302",
    "Caffenero",
    "Imperiale",
    "Leoncino",
    "Panarea",
    "Pepe",
    "TNT",
    "Tornado",
    "TRK",
    "VZ",
    "Zafferano"
  ],
  "Bimota": [
    "HDB",
    "KB1",
    "YB3"
  ],
  "Birmingham Small Arms Company": [
    "Ariel 3",
    "BSA B25",
    "BSA B31",
    "BSA Fury"
  ],
  "BMW": [
    "C 400 GT",
    "C 400 X",
    "C 600",
    "C 650",
    "C 650 GT",
    "CE 02",
    "CE 04",
    "F 650",
    "F 650 CS",
    "F 650 GS",
    "F 650 S",
    "F 700 GS",
    "F 750 GS",
    "F 800 GS",
    "F 800 GT",
    "F 800 R",
    "F 800 S",
    "F 800 ST",
    "F 850 GS",
    "F 900",
    "F 900 GS",
    "F 900 GS Adventure",
    "F 900 GS-P",
    "F 900 R",
    "F 900 XR",
    "F750GS",
    "F850 GS",
    "G 310 GS",
    "G 310 R",
    "G 450 X",
    "G 650",
    "G 650 GS",
    "G310R",
    "HP2",
    "HP4",
    "K 100 LT",
    "K 100 RS",
    "K 100 RT",
    "K 1100 LT",
    "K 1100 RS",
    "K 1200 GT",
    "K 1200 LT",
    "K 1200 R",
    "K 1200 RS",
    "K 1200 S",
    "K 1300 GT",
    "K 1300 R",
    "K 1300 S",
    "K 1600 B",
    "K 1600 GT",
    "K 1600 GTL",
    "M 1000",
    "M 1000 R",
    "M 1000 RR",
    "M 1000 XR",
    "R 100",
    "R 100 CS",
    "R 100 GS",
    "R 100 GSPD",
    "R 100 R",
    "R 100 RS",
    "R 100 RT",
    "R 1100 GS",
    "R 1100 R",
    "R 1100 RS",
    "R 1100 RT",
    "R 1100 S",
    "R 1150 GS",
    "R 1150 R",
    "R 1150 RS",
    "R 1150 RT",
    "R 12",
    "R 12 G/S",
    "R 12 Ninet",
    "R 1200 C",
    "R 1200 CL",
    "R 1200 GS",
    "R 1200 R",
    "R 1200 RS",
    "R 1200 RT",
    "R 1200 S",
    "R 1200 ST",
    "R 1250 GS",
    "R 1250 GS Adventure",
    "R 1250 R",
    "R 1250 RS",
    "R 1250 RT",
    "R 1300 GS",
    "R 1300 GS Adventure",
    "R 1300 R",
    "R 1300 RS",
    "R 1300 RT",
    "R 18",
    "R 18 B",
    "R 18 Classic",
    "R 18 Roctane",
    "R 18 Transcontinental",
    "R 65",
    "R 65 LS",
    "R 80",
    "R 80 GS",
    "R 80 RT",
    "R 80 ST",
    "R 850 R",
    "R 900 RT",
    "R Ninet Scrambler",
    "R100",
    "R1300GS",
    "S 1000 R",
    "S 1000 RR",
    "S 1000 XR"
  ],
  "Brough Superior": [
    "SS100",
    "SS80"
  ],
  "BSA motorcycles": [
    "Triumph TR5MX"
  ],
  "Buell Motorcycle Company": [
    "Buell 1125R"
  ],
  "Bultaco": [
    "155",
    "200",
    "360 24 Hores",
    "Alpina",
    "Astro",
    "Campera",
    "Cazarecords",
    "El Bandido",
    "El Montadero",
    "El Tigre",
    "Frontera",
    "Gaviota",
    "Junior",
    "Lobito",
    "Matador",
    "Mercurio",
    "Metralla",
    "Pursang",
    "Saturno",
    "Senior",
    "Sherpa S",
    "Sherpa T",
    "Streaker",
    "Tirón",
    "Tralla",
    "TSS",
    "TSS MK2"
  ],
  "Česká zbrojovka Strakonice": [
    "ČZ 175/501 Čezeta"
  ],
  "CFMoto": [
    "250SR",
    "300NK",
    "300SS",
    "450CL",
    "450NK",
    "450SS",
    "650",
    "650 Adventura",
    "650NK",
    "675NK",
    "675SS",
    "700CL-X",
    "800NK",
    "CF125",
    "CF300",
    "CF650",
    "CF700",
    "IBEX",
    "IBEX800",
    "Papio"
  ],
  "Curtiss": [
    "V8"
  ],
  "Derbi": [
    "98CC",
    "GP1"
  ],
  "DKW": [
    "Schüttoff L 200",
    "Volksrad ES 200"
  ],
  "DNA Motors": [
    "Daelim VS 125"
  ],
  "Don Vesco": [
    "Big Red",
    "Silver Bird"
  ],
  "Ducati": [
    "1199 Panigale (all)",
    "1299 Superleggera",
    "1299 Superleggera / Panigale",
    "24 Horas",
    "250 Scrambler",
    "350 Scrambler",
    "450 R/T",
    "450 Scrambler",
    "620 Sport",
    "748",
    "749",
    "750 Sport",
    "750SPORT/SS750",
    "750SS",
    "900FE/900CR",
    "900SS",
    "900SSCR/900SSSP",
    "916",
    "98",
    "996",
    "998",
    "999",
    "Classic",
    "D16RR",
    "Deluxe",
    "Desert X",
    "Desertx",
    "Desmo 450 EDX",
    "Desmo 450 MX",
    "Desmosedici GP16",
    "Desmosedici RR",
    "DIAVEL/XDIAVEL",
    "Diavel",
    "Diavel 1260 Lamborghini",
    "GT 1000",
    "Hypermotard",
    "Hypermotard (HYM)",
    "Hypersport (faired Sport Bike)",
    "M600",
    "M620",
    "M750",
    "M900",
    "M900S4",
    "Mach 1",
    "MH900E",
    "Monster",
    "Monster 1200",
    "Monster 1200 / Monster 1200S, Monster 821",
    "Monster 796",
    "Monster 797",
    "MONSTER(NAKED STANDARD BIKE)",
    "Multistrada",
    "Multistrada (MTS)",
    "Multistrada 950",
    "Multistrada 950, Multistrada 1260",
    "New Superbike (SBK)",
    "Panigale",
    "Panigale V2",
    "Panigale V4",
    "Panigale V4 / Panigale V4S / Panigale V4 Speciale",
    "PAULSMART1000LE",
    "Race Only",
    "SBE",
    "Scrambler",
    "Scrambler 800",
    "Scrambler Desert Sled",
    "Scrambler Desert Sled, Ducati Scrambler 1100",
    "Sebring",
    "Sport Touring",
    "SS900/900 SPORT",
    "ST2",
    "ST3",
    "ST4",
    "ST4S",
    "Streetfighter",
    "Streetfighter (SFT)",
    "Super Sport (faired Sport Bike)",
    "Superbike",
    "Supersport",
    "Supersport / Supersport S",
    "Vento",
    "Xdiavel"
  ],
  "Elf Aquitaine": [
    "ELF 500 ROC"
  ],
  "Falcon": [
    "Freedom 250",
    "Techno 125",
    "Wonder 150"
  ],
  "FN": [
    "Four"
  ],
  "Galbusera": [
    "V8"
  ],
  "Garelli": [
    "Ciclone",
    "Enduro 80",
    "Formuno",
    "GSP",
    "Katia",
    "VIP"
  ],
  "Gas Gas": [
    "Gasgas TXT"
  ],
  "Gilera": [
    "Eaglet",
    "H@K",
    "Ice"
  ],
  "Glas": [
    "Goggo Scooters"
  ],
  "Glenn Curtiss": [
    "Curtiss V8"
  ],
  "Gnome et Rhône": [
    "A.B.C. (all British Engine Company Ltd) Motorcycle"
  ],
  "Haojue": [
    "DL250",
    "DR160",
    "HJ125"
  ],
  "Harley-Davidson": [
    "1200 Custom",
    "1200 Custom / 1200 Custom Anniversary",
    "50TH Anniversary Sportster",
    "Bad Boy",
    "Blackline",
    "Blackline 103",
    "Breakout",
    "Breakout 114",
    "CHP",
    "Cross Bones",
    "CVO Breakout",
    "CVO Dyna",
    "CVO Dyna 2",
    "CVO Dyna Wide Glide 2",
    "CVO Dyna Wide Glide 3",
    "CVO Electra Glide",
    "CVO Electra Glide Ultra Limited",
    "CVO Fat Bob 2",
    "CVO Fat Boy",
    "CVO Fat Boy 2",
    "CVO Limited",
    "CVO Pan America",
    "CVO Pro Street Breakout",
    "CVO Road Glide",
    "CVO Road Glide 2",
    "CVO Road Glide Custom",
    "CVO Road Glide Custom 2",
    "CVO Road Glide Limited",
    "CVO Road Glide RR",
    "CVO Road Glide ST",
    "CVO Road Glide Ultra",
    "CVO Road King",
    "CVO Road King 2",
    "CVO Road King 3",
    "CVO Road King 4",
    "CVO Road King 5",
    "CVO Softail Convertible",
    "CVO Softail Convertible 2",
    "CVO Softail Deluxe",
    "CVO Softail Deuce",
    "CVO Softail Deuce 2",
    "CVO Softail Springer",
    "CVO Softail Springer 2",
    "CVO Softail Springer 3",
    "CVO Street Glide",
    "CVO Street Glide 2",
    "CVO Street Glide Special",
    "CVO Super Glide 4",
    "CVO Tri Glide",
    "CVO Ultra Classic Electra Glide",
    "CVO Ultra Classic Electra Glide 3",
    "CVO Ultra Classic Electra Glide 4",
    "CVO Ultra Classic Electra Glide 5 / CVO Ultra Classic Ltd",
    "CVO Ultra Classic Electra Glide 8",
    "CVO Ultral Classic Electra Glide 6",
    "CVO V-ROD",
    "CVO V-ROD 2",
    "Deluxe",
    "Disc Glide",
    "Dyna Convertible",
    "Dyna Fat Bob",
    "Dyna Low Rider",
    "Dyna Street Bob",
    "Dyna Super Glide",
    "Dyna Super Glide 35TH Anniversary",
    "Dyna Super Glide Custom",
    "Dyna Super Glide Police",
    "Dyna Super Glide Sport",
    "Dyna Super Glide T-SPORT",
    "Dyna Wide Glide",
    "Dyna Wide Glide 105TH Anniversary",
    "Electra Glide",
    "Electra Glide Classic",
    "Electra Glide Classic 100TH Anniversary / Electra Glide Classic",
    "Electra Glide Classic 103",
    "Electra Glide Classic Shrine",
    "Electra Glide Highway King",
    "Electra Glide Standard",
    "Electra Glide Ultra Classic",
    "Electra Glide Ultra Classic 103",
    "Electra Glide Ultra Classic 103 Shrine",
    "Electra Glide Ultra Classic Shrine",
    "Electra Glide Ultra Limited",
    "Electra Glide Ultra Limited Shrine",
    "Fat Bob",
    "Fat Bob 114",
    "Fat Boy",
    "Fat Boy 103",
    "Fat Boy 114",
    "Fat Boy Anniversary",
    "Fat Boy Lo",
    "Fat Boy Lo 103",
    "Fat Boy Shrine",
    "FLD103 / Switchback",
    "FLFBS ANV / 115TH Anniversary Fat Boy 114",
    "FLFBS ANX / 115TH Anniversary Fat Boy 114",
    "FLH",
    "FLHC / Heritage Classic",
    "FLHCS ANV / 115TH Anniversary Heritage Classic 114",
    "FLHP",
    "FLHP / Police Road King",
    "FLHPE / Electra Glide Standard Police",
    "FLHPEI",
    "FLHPI",
    "FLHR",
    "FLHR / Road King",
    "FLHRC / Road King Classic",
    "FLHRC103 / Road King Classic 103",
    "FLHRCI",
    "FLHRCI / Road King Classic",
    "FLHRI / Road King",
    "FLHRXS / Road King Special",
    "FLHS",
    "FLHT / Electra Glide Standard",
    "FLHTC / Electra Glide Classic",
    "FLHTC Ultra",
    "FLHTC Ultra W/SHRINE",
    "FLHTC Ultra W/SIDECAR",
    "FLHTC W/FAIRING (police)",
    "FLHTC W/SHRINE",
    "FLHTCI",
    "FLHTCI / Electra Glide Classic",
    "FLHTCI / FLHTCI Anniversary",
    "FLHTCU / Electra Glide Ultra Classic",
    "FLHTCUI",
    "FLHTCUI / FLHTCUI Anniversary",
    "FLHTCUI / Ultra Classic Electra Glide",
    "FLHTCUI W/SHRINE",
    "FLHTCUI W/SIDECAR",
    "FLHTCUI W/SIDECAR / FLHTCUI W/SIDECAR Anniversary",
    "FLHTCUL / Electra Glide Ultra Classic Low",
    "FLHTCUTG / Tri Glide Ultra",
    "FLHTCUTG / Tri Glide Ultra Classic",
    "FLHTCUTG ANV / 115TH Anniversary Tri Glide Ultra",
    "FLHTK / Ultra Limited",
    "FLHTK ANV / 115TH Anniversary Ultra Limited",
    "FLHTK SHRINE / Ultra Limited Shrine",
    "FLHTK SHRINE / Ultra Limited Special Edition",
    "FLHTKL / Ultra Limited Low",
    "FLHTKSE ANV / 115TH Anniversary CVO Limited",
    "FLHTP / Electra Glide Standard Police",
    "FLHTP W / Windshield (police)",
    "FLHTPI / Electra Glide Standard Police",
    "FLHX",
    "FLHX / Street Glide",
    "FLHXS / Street Glide Special",
    "FLHXSE / CVO Street Glide",
    "FLHXST / Street Glide ST",
    "FLRT / Freewheeler",
    "FLS103 / Softail Slim",
    "FLSL / Softail Slim",
    "FLSS / Softail Slim S",
    "FLST / Heritage Softail",
    "FLSTC / Heritage Softail Classic",
    "FLSTC103 / Heritage Softail Classic",
    "FLSTCI / Heritage Softail Classic",
    "FLSTF / Fat Boy",
    "FLSTF103 / Fat Boy",
    "FLSTFB103 / Fat Boy Lo",
    "FLSTFBS / Fat Boy S",
    "FLSTFI / Fat Boy",
    "FLSTN",
    "FLSTN103 / Softail Deluxe",
    "FLSTS / Heritage Springer",
    "FLSTSI / Heritage Springer",
    "FLT",
    "FLTC",
    "FLTC Ultra",
    "FLTCUI",
    "FLTR / Road Glide",
    "FLTRI / Road Glide",
    "FLTRI/FLTRI Anniversary",
    "FLTRK / Road Glide Limited",
    "FLTRT / Road Glide",
    "FLTRU / Road Glide Ultra",
    "FLTRUSE / CVO Road Glide Ultra",
    "FLTRX / Road Glide",
    "FLTRXSE / CVO Road Glide",
    "FLTRXST / Road Glide ST",
    "FORTY-EIGHT",
    "FORTY-EIGHT Special",
    "Freewheeler",
    "FXB",
    "FXBB / Street Bob",
    "FXBR / Breakout",
    "FXBRS ANX / 115TH Anniversary Breakout 114",
    "FXD",
    "FXDB / Dyna Glide",
    "FXDB / Dyna Street Bob",
    "FXDBI / Dyna Street Bob",
    "FXDBP103 / Dyna Street Bob",
    "FXDC",
    "FXDF103 / Fat Bob",
    "FXDFSE / Fat Bob",
    "FXDG",
    "FXDL / Dyna Low Rider",
    "FXDL103 / Low Rider",
    "FXDLI / Dyna Low Rider",
    "FXDLS / Low Rider S",
    "FXDR 114",
    "FXDS Conv",
    "FXDWG",
    "FXDWG/FXDWG Anniversary",
    "FXDX",
    "FXE",
    "FXEF",
    "FXFB / Fat Bob",
    "FXLR",
    "FXLR / Low Rider",
    "FXLRS / Low Rider S",
    "FXLRST / Low Rider ST",
    "FXR2",
    "FXR3",
    "FXRC",
    "FXRD",
    "FXRDG",
    "FXRP",
    "FXRP Sidecar Alone (also Called RLE)",
    "FXRS",
    "FXRT",
    "FXS",
    "FXSB",
    "FXSB103 / BREAKOUT",
    "FXST",
    "FXST / Softail Standard",
    "FXSTB / Night Train",
    "FXSTC",
    "FXSTD / Softail Deuce",
    "FXSTS / Springer Softail",
    "FXSTSB",
    "FXWG",
    "Harley Davidson 250RR",
    "Heritage Classic",
    "Heritage Classic 114",
    "Heritage Softail",
    "Heritage Softail Classic",
    "Heritage Softail Classic 103",
    "Heritage Softail Classic 103 Shrine",
    "Heritage Softail Classic Shrine",
    "Heritage Springer",
    "Hummer",
    "HYDRA-GLIDE Revival",
    "Iron 1200",
    "Iron 883",
    "Low Glide Custom",
    "Low Rider",
    "Low Rider EL Diablo",
    "Low Rider S",
    "Low Rider ST",
    "Military",
    "Model 8-VALVE Board Track Racer",
    "Model W",
    "MT500",
    "Night Rod",
    "Night Rod Special",
    "Night Rod Special W/ABS",
    "Night Rod W/ABS",
    "Night Train",
    "Nightster",
    "Nightster Special",
    "Pan America",
    "Pan America Special",
    "Police Electra Glide",
    "Police Pursuit Glide",
    "Police Road Glide",
    "Police Road King",
    "Revival",
    "RLE",
    "Road Glide",
    "Road Glide 3",
    "Road Glide Custom",
    "Road Glide Custom 103",
    "Road Glide Limited",
    "Road Glide Special",
    "Road Glide ST",
    "Road Glide Ultra",
    "Road Glide Ultra 103",
    "Road King",
    "Road King 103",
    "Road King 103 Shrine",
    "Road King Classic",
    "Road King Custom",
    "Road King Shrine",
    "Road King Special",
    "Rocker",
    "Rocker C",
    "SCREAMIN' Eagle Road King",
    "SCREAMIN' Eagle Ultra Classic Electra Glide",
    "SEVENTY-TWO",
    "Shrine Street Glide",
    "Sidecar For FLHR/I",
    "Sidecar For FLHRCI",
    "Sidecar For FLHRS/I",
    "Sidecar For FLHT FLTH/I",
    "Sidecar For FLHTC/I",
    "Sidecar For FLHX/I",
    "Sidecar For FLTR/I",
    "Sidecar For ULTRA",
    "Softail Custom",
    "Softail Deluxe",
    "Softail Deluxe 103",
    "Softail Deuce",
    "Softail Slim",
    "Softail Slim 103",
    "Softail Springer",
    "Softail Springer Classic",
    "Softail Standard",
    "Sport Glide",
    "Sportster",
    "Sportster 1200",
    "Sportster 1200 Custom",
    "Sportster 1200 Custom HD1 Base",
    "Sportster 1200 Low",
    "Sportster 1200 Roadster",
    "Sportster 1200 Sport",
    "Sportster 883",
    "Sportster 883 Custom",
    "Sportster 883 Hugger",
    "Sportster 883 Low",
    "Sportster 883 Superlow",
    "Sportster 883R",
    "Sportster S",
    "Sportster Superlow",
    "Sportster XL1200 Superlow",
    "Sportster XL883 Low",
    "Sportster XR1200",
    "Springer Softail",
    "Street 500",
    "Street 750",
    "Street Bob",
    "Street Bob 114",
    "Street Glide",
    "Street Glide 103",
    "Street Glide Special",
    "Street Glide ST",
    "Street Glide Trike",
    "Street Glide Ultra",
    "Street Rod",
    "Super Glide",
    "Superlow",
    "Superlow 1200T",
    "Switchback",
    "TLE",
    "TLE For FLHR",
    "TLE For FLHRCI",
    "TLE For FLHT",
    "TLE For FLHTC",
    "TLE Ultra",
    "Tri Glide Ultra",
    "Tri Glide Ultra Classic",
    "Ultra Classic Electra Glide",
    "Ultra Classic Low",
    "Ultra Limited",
    "Ultra Limited Low",
    "V-ROD",
    "V-ROD 100TH Anniversary / V-ROD",
    "V-ROD Destroyer",
    "V-ROD Muscle",
    "V-ROD W/ABS",
    "VRSCDX / NIGHT ROD SPECIAL",
    "VRSCF / V-ROD MUSCLE",
    "VRXSE",
    "Wide Glide",
    "X350RA",
    "XA",
    "XG750A / Street Rod",
    "XL 1200",
    "XL 883 / Sportster 883",
    "XL1200C/SPORSTER 1200 CUSTOM",
    "XL1200C/XL1200C Anniversary",
    "XL1200CP / SPORSTER 1200 CUSTOM",
    "XL1200S",
    "XL1200T / SUPERLOW 1200T",
    "XL1200V / SEVENTY-TWO",
    "XL1200X / FORTY-EIGHT",
    "XL883L / SUPERLOW",
    "XL883R",
    "XLH",
    "XLH 883",
    "XLH-1100",
    "XLX",
    "XR-750",
    "XR1000",
    "XR1200",
    "XR1200X"
  ],
  "Hero": [
    "Pleasure"
  ],
  "Honda": [
    "ADV150",
    "ADV160",
    "Africa Twin",
    "Africa Twin Adventure Sports",
    "CB-1",
    "CB1000",
    "CB1000F",
    "CB1000R",
    "CB1100",
    "CB1100A",
    "CB1100SA",
    "CB125",
    "CB300",
    "CB300F",
    "CB300FA",
    "CB300R",
    "CB450",
    "CB500",
    "CB500 Hornet",
    "CB500F",
    "CB500FA",
    "CB500X",
    "CB500XA",
    "CB50R",
    "CB550",
    "CB599",
    "CB650",
    "CB650F",
    "CB650R",
    "CB650RA",
    "CB700",
    "CB750",
    "CB750 (nighthawk 750)",
    "CB900",
    "CB900 (hornet)",
    "CBF1000",
    "CBF300",
    "CBF300N",
    "CBF600",
    "CBR1000F",
    "CBR1000RA",
    "CBR1000RR",
    "CBR1000S",
    "CBR1100X",
    "CBR125",
    "CBR125R",
    "CBR250",
    "CBR250R",
    "CBR250RA",
    "CBR300",
    "CBR300R",
    "CBR300RA",
    "CBR500",
    "CBR500R",
    "CBR500RA",
    "CBR600",
    "CBR600F",
    "CBR600RA",
    "CBR600RR",
    "CBR650",
    "CBR650F",
    "CBR650FA",
    "CBR650R",
    "CBR650RA",
    "CBR900/CBR954",
    "CBR900RR",
    "CBR929RR",
    "CBR954RR",
    "CBX",
    "CHF50",
    "CMX300 (rebel 300)",
    "CMX500 (rebel 500)",
    "CRF1000",
    "CRF1000 (africa Twin)",
    "CRF1000A",
    "CRF1000A2",
    "CRF1000AS",
    "CRF1000ASD",
    "CRF1000D",
    "CRF1000D2",
    "CRF1000LA",
    "CRF1000LD",
    "CRF100F",
    "CRF110",
    "CRF1100 (africa Twin)",
    "CRF11004",
    "CRF11004D",
    "CRF1100A",
    "CRF1100A4",
    "CRF1100D",
    "CRF1100D4",
    "CRF1100L",
    "CRF1100L4",
    "CRF1100L4D",
    "CRF1100LD",
    "CRF110F",
    "CRF125",
    "CRF125F",
    "CRF125FB",
    "CRF150",
    "CRF150F",
    "CRF150R",
    "CRF150RB",
    "CRF150RBE",
    "CRF150RE",
    "CRF230F",
    "CRF230L",
    "CRF230M",
    "CRF250",
    "CRF250F",
    "CRF250L",
    "CRF250LA",
    "CRF250R",
    "CRF250RB",
    "CRF250RL",
    "CRF250RLA",
    "CRF250RX",
    "CRF250X",
    "CRF300F",
    "CRF300L",
    "CRF450",
    "CRF450L",
    "CRF450R",
    "CRF450RB",
    "CRF450RL",
    "CRF450RWE",
    "CRF450RX",
    "CRF450X",
    "CRF50",
    "CRF50F",
    "CRF70F",
    "CRF80F",
    "Dio",
    "DJ-1",
    "Dunk",
    "FC50",
    "Forza",
    "GL1500A (GOLD WING ASPENCADE)",
    "GL1500SE (GOLD WING SE)",
    "Gold Wing",
    "Gold Wing Interstate",
    "Gold Wing Tour",
    "Joker",
    "Motocompacto",
    "NC50",
    "NC700JD (NM4)",
    "NC700S",
    "NC700X",
    "NC700XD",
    "NC700XD (NC700X DCT)",
    "NC700XD/NC700X",
    "NC700XDL (NC700X DCT)",
    "NC700XDL/NC700X",
    "NC700XL (NC700X)",
    "NC750S",
    "NC750X",
    "NSR250",
    "NSS300 (FORZA)",
    "NSS300A (FORZA)",
    "NT1100",
    "NX125",
    "NX250",
    "NX500",
    "NX650",
    "PCX",
    "PCX125",
    "PCX150",
    "Rebel",
    "Rebel 1100",
    "Rebel 300",
    "Rebel 500",
    "SCL500",
    "SH150D/SH150I",
    "SH150I",
    "SH50",
    "Tact",
    "Today",
    "Transalp",
    "Varadero",
    "VF",
    "WW150/PCX150",
    "X-ADV",
    "XRV 650 Africa Twin"
  ],
  "Husqvarna": [
    "701 Enduro",
    "701 Enduro, LR",
    "701 Supermoto",
    "A1",
    "A2",
    "Closed Course Competition",
    "Enduro",
    "FOUR-STROKE",
    "LC4 Supermoto",
    "MC 258",
    "Norden 901",
    "Pioneer",
    "SM",
    "SM 450 R",
    "SM 510 R",
    "SM 610 R",
    "SM 630",
    "SMR 449",
    "SMR 511",
    "Street Legal Enduro",
    "SVARTPILEN/VITPILEN",
    "Svartpilen",
    "Svartpilen 401",
    "Svartpilen 701",
    "Svartpilen 801",
    "TE",
    "TE 250",
    "TE 310",
    "TE 449",
    "TE 450",
    "TE 510",
    "TE 511",
    "TE 610",
    "TE 630",
    "TWO-STROKE",
    "TX 300",
    "Vektorr",
    "Vitpilen",
    "Vitpilen 401",
    "Vitpilen 701",
    "WR 300"
  ],
  "Hyosung": [
    "GD250N",
    "GT250R",
    "GT650",
    "GT650R",
    "GV250 Aquila",
    "GV300S Aquila",
    "GV650 Aquila",
    "RT 125",
    "RT125D Karion",
    "ST7"
  ],
  "Ilmor": [
    "X3"
  ],
  "Indian": [
    "101 Scout",
    "Centennial Chief",
    "Centennial Scout",
    "Challenger",
    "Challenger Dark Horse",
    "Challenger Elite",
    "Challenger Limited",
    "Chief",
    "Chief Bobber",
    "Chief Bobber Dark Horse",
    "Chief Centennial",
    "Chief Classic",
    "Chief Dark Horse",
    "Chief Deluxe",
    "Chief Roadmaster",
    "Chief Special Edition",
    "Chief STANDARD/SPRINGFIELD",
    "Chief T3 Special Edition",
    "Chief Vintage",
    "Chieftain",
    "Chieftain Classic",
    "Chieftain Dark Horse",
    "Chieftain ELITE/JACK DANIEL'S Limited Edition Indian Chieftain",
    "Chieftain Elite",
    "Chieftain Limited",
    "Chieftain Powerplus",
    "Chieftan",
    "FTR",
    "FTR 1200",
    "FTR 1200 Rally",
    "FTR 1200 S",
    "FTR 1200 S Race Replica",
    "FTR X RSD Super Hooligan",
    "FTR Z",
    "Jack DANIEL'S Limited Edition Chief Bobber Dark Horse",
    "Jack DANIEL'S Limited Edition Roadmaster",
    "Jack DANIEL'S Limited Edition Scout Bobber",
    "Powerplus",
    "Pursuit",
    "Pursuit Dark Horse",
    "Pursuit Limited",
    "Roadmaster",
    "Roadmaster Dark Horse",
    "Roadmaster Elite",
    "Roadmaster Limited",
    "Roadmaster Powerplus",
    "Scout",
    "Scout ABS",
    "Scout Bobber",
    "Scout Bobber ABS",
    "Scout Bobber Sixty",
    "Scout Bobber Sixty ABS",
    "Scout Bobber Twenty",
    "Scout Bobber Twenty ABS",
    "Scout Centennial",
    "Scout Classic",
    "Scout Rigid",
    "Scout Rogue",
    "Scout Rogue Sixty",
    "Scout Rogue Sixty ABS",
    "Scout Sixty",
    "Scout Sixty ABS",
    "Scout Sixty Bobber",
    "Scout Sixty Classic",
    "Scout Special Edition",
    "Scout STANDARD/DELUXE/SPRINGFIELD",
    "Spirit Special Edition",
    "Spirit STANDARD/DELUXE/RAODMASTER/SPRINGFIELD",
    "Sport Chief",
    "Sport Scout",
    "Sport Scout Sixty",
    "Springfield",
    "Springfield Dark Horse",
    "Super Chief",
    "Super Chief Limited",
    "Super Scout",
    "Vintage",
    "Vintage Dark Horse"
  ],
  "Industriewerke Ludwigsfelde": [
    "IWL Pitty",
    "IWL SR56 Wiesel",
    "IWL Troll 1"
  ],
  "Innocenti": [
    "Lambretta Li 125 Special"
  ],
  "Italjet": [
    "Dragster",
    "Jet Set",
    "Velocifero"
  ],
  "James Cycle Co": [
    "James Autocycle"
  ],
  "Jawa": [
    "350/360",
    "90"
  ],
  "Kawasaki": [
    "EL250 Eliminator",
    "Eliminator",
    "Eliminator 125",
    "Eliminator 600",
    "GPZ 400",
    "H2R",
    "KLR250",
    "KLR600",
    "KLR650",
    "KX",
    "Ninja 1000",
    "Ninja 1000SX",
    "Ninja 1100",
    "Ninja 1100SX",
    "Ninja 250R",
    "Ninja 300",
    "Ninja 400",
    "Ninja 500",
    "Ninja 500R",
    "Ninja 600",
    "Ninja 600R",
    "Ninja 650",
    "Ninja 650R",
    "Ninja 7",
    "Ninja 7 Hybrid",
    "Ninja 900",
    "Ninja E-1",
    "Ninja H2",
    "Ninja H2 R",
    "Ninja H2 SX",
    "Ninja ZX-10R",
    "Ninja ZX-10RR",
    "Ninja ZX-11",
    "Ninja ZX-12R",
    "Ninja ZX-14",
    "Ninja ZX-14R",
    "Ninja ZX-4R",
    "Ninja ZX-6",
    "Ninja ZX-6R",
    "Ninja ZX-9R",
    "Versys",
    "Versys 1000",
    "Versys 1100",
    "Versys 650",
    "VERSYS-X 250/300",
    "VERSYS-X 300",
    "VN 1500",
    "VN 800",
    "VN 800 Drifter",
    "Vulcan 1500",
    "Vulcan 1600",
    "Vulcan 1700",
    "Vulcan 2000",
    "Vulcan 500",
    "Vulcan 700",
    "Vulcan 750",
    "Vulcan 800",
    "Vulcan 88",
    "Vulcan 900",
    "Vulcan S",
    "W800",
    "Z125 PRO",
    "Z300",
    "Z400",
    "Z500",
    "Z650",
    "Z900",
    "ZL1000 Eliminator",
    "ZL600 Eliminator",
    "ZL900 Eliminator",
    "ZX-12R",
    "ZX-6R",
    "ZX-6RR",
    "ZX-7R",
    "ZX-7RR"
  ],
  "Keeway": [
    "Arron",
    "Beso",
    "Bravo",
    "Buccaneer",
    "Cappucino",
    "Flamenco",
    "Formula",
    "Martrix",
    "Mojito",
    "Retrostar",
    "SC",
    "Shadowstar",
    "Shiny",
    "Sixties",
    "Titan",
    "V-BOB",
    "Versilia",
    "Vieste",
    "Vieste (vmaxie)",
    "Vieste XDV"
  ],
  "Kral": [
    "KR-11",
    "KR-23",
    "KR-25"
  ],
  "KTM": [
    "1090 Adventure",
    "1090 Adventure R",
    "1190 Adv",
    "1190 Adventure",
    "1190 Adventure R",
    "390 Duke",
    "690 Duke",
    "690 Enduro",
    "690 SMC",
    "790 Adventure",
    "790 Adventure R",
    "790 Duke",
    "790/890 Adv",
    "790/890 Adv R, Rally",
    "790/890 Adv, SMT",
    "790/890 Duke, R",
    "950/990 Adv",
    "950/990 Supermoto",
    "990 Duke",
    "990 RC R",
    "Adventure",
    "Adventure + Adventure R",
    "Adventure + Rally",
    "Closed Course Competition",
    "Competition",
    "Duke",
    "Enduro FOUR-STROKE",
    "Enduro FOUR-STROKE/EXC-R",
    "Enduro TWO-STROKE",
    "FREERIDE",
    "Freeride E-XC",
    "Gelande Sport",
    "LC4 660R",
    "LC4 Duke",
    "LC4 Enduro",
    "LC4 Engine 1-1ST Version",
    "LC4 Engine SMC",
    "LC8 Adventure",
    "LC8 Supermoto",
    "Minis",
    "R-RACING F-ECF-F",
    "R2R",
    "Racing",
    "Rally",
    "RC",
    "RC16",
    "RC250GP",
    "RC8, RC8 R",
    "Single Cylinder LC4 Duke",
    "Street Legal Enduro",
    "Super Adventure",
    "Super Adventure R/S",
    "Super Adventure S",
    "Super Adventure T",
    "Super Duke GT",
    "Super Duke R",
    "Super Enduro",
    "Unit",
    "V-ENGINE Duke",
    "V-TWIN LC8 Adventure",
    "V-TWIN LC8 Supermoto",
    "V-TWIN RC8 + RC8 R",
    "V-TWIN RC8 Adventure",
    "V-TWIN RC8 Adventure R",
    "V-TWIN RC8 Super Duke R"
  ],
  "Kuba": [
    "Bluebird",
    "Brilliant 125 Pro",
    "Cruiser 250",
    "Superlight 200",
    "TK03",
    "Trendy 50"
  ],
  "Kyiv Motorcycle Plant": [
    "K1B"
  ],
  "Kymco": [
    "16\" Flat Bed Scooter",
    "Agility",
    "Agility City",
    "AK 550",
    "AK 550I",
    "AK 575",
    "AK550",
    "AK575",
    "B&W",
    "Compagno",
    "CV3",
    "Downtown",
    "F9",
    "Flat Bed Scooter",
    "Grandvista",
    "K-PIPE",
    "Like",
    "Like 200 / Compagno 200",
    "Like 200I / Like 200I LX",
    "Like 50 (4T) / Like 150",
    "Like 50 / Compagno 50",
    "Like 50 / M50 / A-TOWN 50",
    "Movie",
    "Myroad",
    "People",
    "People 50 2T",
    "PEOPLE 50 2T,PEOPLE 50",
    "People S 50 4T",
    "Quannon",
    "Sento",
    "Spade",
    "Step Over Frame",
    "Sting",
    "Super 8",
    "Super 8 150",
    "Super 8 50",
    "Super 8-50 2T",
    "Super 9",
    "TOMOS/KYMCO Products",
    "Venox",
    "Vitality",
    "Vitality 50 4T",
    "X-TOWN",
    "Xciting",
    "Yager"
  ],
  "Lambretta": [
    "Due",
    "GP/DL",
    "Model B",
    "UNO"
  ],
  "Laverda": [
    "1000 3C",
    "1200"
  ],
  "Mahindra & Mahindra": [
    "Mahindra MGP3O"
  ],
  "Malaguti": [
    "Centro",
    "Ciak",
    "Crosser",
    "F18 Warrior",
    "Fifty",
    "Madison",
    "Password",
    "Phantom",
    "Yesterday"
  ],
  "Mash Motors": [
    "Mash Five Hundred 400"
  ],
  "MBK": [
    "Evolis"
  ],
  "Montesa": [
    "150",
    "250 Trial",
    "250CC Twin",
    "A-45",
    "B-46/49",
    "Brio",
    "Cappra",
    "Ciclo",
    "Cota",
    "Cota 123",
    "Cota 172",
    "Cota 200",
    "Cota 247",
    "Cota 25",
    "Cota 300RR",
    "Cota 310",
    "Cota 311",
    "Cota 315R",
    "Cota 330",
    "Cota 348",
    "Cota 349",
    "Cota 49",
    "Cota 4RT",
    "Cota 74",
    "Crono",
    "D-51",
    "Enduro",
    "Fura",
    "Impala",
    "Impala Cross",
    "Impala Kenya",
    "King Scorpion",
    "LA Cross 66",
    "Microscooter",
    "Rapita",
    "Sprint",
    "Texas"
  ],
  "Moto Guzzi": [
    "1000 SP II, Mille GT",
    "850 Le Mans III",
    "850 T3",
    "850 T5",
    "Airone",
    "Albatros",
    "Astore",
    "Audace",
    "Breva 1100",
    "Breva 1200",
    "Breva 750",
    "California 1100",
    "California 1100 Black Eagle",
    "California 1100 Vintage",
    "California 1400 Custom",
    "California 1400 Touring",
    "California 1400 Touring SE",
    "California II",
    "California III",
    "Colibrì",
    "CX 100 (le Mans)",
    "Eldorado",
    "G.P.",
    "GP 500",
    "Griso 1100",
    "Griso 1200 8V",
    "Griso 1200 8V SE",
    "Le Mans 1000, Le Mans SE",
    "MGX-21",
    "Nevada 750",
    "Norge",
    "Norge 1200",
    "Norge GT 8V",
    "Nuovo Falcone",
    "Stelvio",
    "Stelvio 1200",
    "Stelvio 1200 4V",
    "Stelvio 1200 8V NTX",
    "Stelvio 1200 8V NTX ABS",
    "Trialce",
    "V100",
    "V1000 Convert, V1000 G5, V1000 SP",
    "V11",
    "V50 III",
    "V50 Monza",
    "V65 Custom",
    "V65 Lario",
    "V65 TT",
    "V65, V65 SP",
    "V7",
    "V7 750",
    "V7 Cafe Classic",
    "V7 Classic",
    "V7 II Racer",
    "V7 II Special",
    "V7 II Stone",
    "V7 III",
    "V7 III Anniversario",
    "V7 III Carbon (dark Colored)",
    "V7 III Carbon (shine Colored)",
    "V7 III Milano",
    "V7 III Racer",
    "V7 III Racer (10TH Anniversary)",
    "V7 III Rough",
    "V7 III Special",
    "V7 III Special SE",
    "V7 III Stone",
    "V7 III Stone (night Pack)",
    "V7 III Stone SE",
    "V7 Racer",
    "V7 Special",
    "V7 Stone",
    "V85",
    "V85 TT",
    "V9 Bobber",
    "V9 Bobber Sport",
    "V9 Roamer"
  ],
  "Motolux": [
    "F5 125",
    "MRS 125",
    "MT 125",
    "Nirvana 125",
    "Rossi 50"
  ],
  "MV Agusta": [
    "125 SOHC",
    "RVS#1"
  ],
  "MZ Motorrad- und Zweiradwerk": [
    "MZ ETS 125/150",
    "MZ ETS 175/250"
  ],
  "Norton Motorcycle Company": [
    "Norton Classic",
    "Norton Model 7 Dominator",
    "Norton Model 88 Dominator",
    "Norton Model 99 Dominator",
    "Norton Nortonette",
    "NORTON-PEUGEOT"
  ],
  "NSU Motorenwerke": [
    "NSU Lambretta Scooters"
  ],
  "Ossa": [
    "125",
    "150",
    "160",
    "175 Sport",
    "230 Racing",
    "230 Sport",
    "250",
    "Desert",
    "Motoball",
    "Ossita 50",
    "Pluma",
    "Stiletto",
    "Super Pioneer",
    "Tri",
    "Urbe",
    "Yankee"
  ],
  "Państwowe Zakłady Inżynierii": [
    "Sokół 1000",
    "Sokół 200",
    "Sokół 500",
    "Sokół 600"
  ],
  "Peugeot": [
    "Kisbee",
    "V-CLIC",
    "Vivacity"
  ],
  "Phelon & Moore": [
    "Panther Model 100",
    "Panther Model 120",
    "Panther Model 75"
  ],
  "Piaggio": [
    "Carnaby",
    "Free",
    "Liberty",
    "Medley",
    "MP3",
    "Typhoon",
    "Vespa",
    "Vespa 150 GS",
    "Vespa 50 Special",
    "Vespa Rally 180",
    "Vespa Rally 200",
    "X7",
    "X8",
    "Zip"
  ],
  "Pierce-Arrow": [
    "Pierce Four"
  ],
  "Pope Manufacturing Company": [
    "Pope Model L"
  ],
  "PZL-Świdnik": [
    "Wiejski Popierdalacz"
  ],
  "QJMotor": [
    "ATR",
    "EZ",
    "Fort",
    "G2",
    "LTR",
    "SFA",
    "SRF",
    "SRK",
    "SRT",
    "SRV",
    "SVT",
    "VPS"
  ],
  "Ramzey": [
    "GQ 125-20",
    "Mopet 100",
    "QM 125T-10D"
  ],
  "RKS": [
    "125N",
    "A250",
    "Bitter 125",
    "BLACKSTER 250",
    "BLACKSTER 250i",
    "BLACKSTER Chopper",
    "BLACKWOLF",
    "BLADE 250",
    "C1002V",
    "DES125",
    "FORT250",
    "Freccia 150",
    "GTR50",
    "ICON 50 ST",
    "K-LIGHT 250",
    "LINCE125",
    "LT50PRO PLUS",
    "LTM125",
    "LTR125",
    "M250",
    "M502N",
    "NEON125",
    "Newlight 125",
    "PARMIDA 50",
    "R250",
    "REALE125",
    "REALE125X",
    "RK125S",
    "RK250S",
    "RODOS",
    "ROSA 50 PRO",
    "RSIII Pro",
    "RT250",
    "RZ125",
    "RZ125X",
    "RZ150",
    "RZ150X",
    "RZ250S",
    "SC150RE",
    "Spontini 110",
    "SRK125R",
    "SRK125S",
    "SRK250",
    "SRK250RR",
    "SRK250RS",
    "SRK250S",
    "SRK400RR",
    "SRK450RA",
    "SRK550",
    "SRK550RS",
    "SRT800SX",
    "SRT900SX",
    "SRT902S",
    "SRV125",
    "SRV250VS",
    "SRV700",
    "SVT650X",
    "Titanic 150",
    "VIESTE 249",
    "VPS125 PRO",
    "VRS125"
  ],
  "Royal Enfield": [
    "Bullet",
    "Classic",
    "Continental GT",
    "Continental GT Twin",
    "Electra",
    "Himalayan",
    "Hunter 350",
    "INT 650",
    "INT Bear 650",
    "Interceptor 650",
    "J1H",
    "Meteor",
    "Scram 411",
    "Scram 440",
    "Shotgun 650",
    "Super Meteor 650",
    "Thunderbird",
    "WD/RE"
  ],
  "Salcano": [
    "Capri 50",
    "Nova 50",
    "Wolf 125",
    "XRS 125"
  ],
  "Schüttoff motorcycles": [
    "Schüttoff L 200"
  ],
  "Segway": [
    "E110"
  ],
  "Sheffield-Simplex": [
    "NER-A-CAR Type CK1 Motorcycle"
  ],
  "SHL": [
    "M11",
    "M17 Gazela"
  ],
  "Suter Racing Technology": [
    "Suter MMX3"
  ],
  "Suzuki": [
    "Burgman",
    "Burgman 200",
    "Burgman 400",
    "Burgman 650",
    "DL1000",
    "DL1000A/DL1000AA",
    "DL1000AL/DL1000AAL",
    "DL1000K",
    "DL1000L",
    "DL1000XAAL9 (V-STROM 1000XT Adventure)",
    "DL1050",
    "DL650",
    "DL650A",
    "DL650AAL/DL650AL",
    "DL650AL",
    "DL650K",
    "DL650L",
    "DL650XA/DL650A",
    "DL650XAAL9 (V-STROM 650XT Touring)",
    "DL650XAL/DL650AAL/DL650AL",
    "DL650XAL7",
    "Gixxer",
    "Gixxer 250",
    "GSF1250SA/GSX1250SA",
    "GSX",
    "GSX-8R",
    "GSX-8S",
    "GSX-8T",
    "GSX-8TT",
    "GSX-R1000",
    "GSX-R1000AL",
    "GSX-R1000K",
    "GSX-R1000L",
    "GSX-R1000R",
    "GSX-R1100",
    "GSX-R1100W",
    "GSX-R125",
    "GSX-R600",
    "GSX-R600K",
    "GSX-R600L",
    "GSX-R600W",
    "GSX-R750",
    "GSX-R750K",
    "GSX-R750L",
    "GSX-R750W",
    "GSX-S1000",
    "GSX-S1000A",
    "GSX-S1000AL7",
    "GSX-S1000AL8 / GSX-S1000ZAL8",
    "GSX-S1000AL9/GSXS1000ZAL9/GSXS1000YAL9",
    "GSX-S1000F",
    "GSX-S1000FA",
    "GSX-S1000FAL7",
    "GSX-S1000FAL8",
    "GSX-S1000GT/GSX-S1000GT+",
    "GSX-S1000GT+",
    "GSX-S750",
    "GSX-S750L8",
    "GSX-S750ZAL8 / GSX-S750L8",
    "GSX-S750ZL/GSX-S750L",
    "GSX-S750ZL9 (49ST)",
    "GSX-Z750ZAL9 (50ST) / GSX-S750YAL9 (50ST) / GSX-S750ZL9 (50ST)",
    "GSX1100",
    "GSX1100G",
    "GSX1250FA",
    "GSX1250FAL",
    "GSX1300 RK5",
    "GSX1300BK",
    "GSX1300BKA",
    "GSX1300R",
    "GSX1300RAL",
    "GSX1300RAL/GSX1300RAZL",
    "GSX1300RK",
    "GSX1300RL",
    "GSX1300RL/GSX1300RZL",
    "GSX1300RRM2 / GSX1300RRZM2",
    "GSX250R",
    "GSX600F",
    "GSX600F/GSX600FT",
    "GSX600FK",
    "GSX650F",
    "GSX650FA",
    "GSX750F",
    "GSX750F/GSX750FT",
    "GSX750FK",
    "GSXS1000FZL9",
    "GSXS1000SM0",
    "GSXS1000SM1",
    "Katana",
    "Katana AY50",
    "Nex",
    "Sepia",
    "Skydrive",
    "Spin",
    "SV650",
    "SV650/SV650S",
    "SV650/SV650S/SV650SF",
    "SV650A/SV650SA",
    "SV650A/SV650SA/SV650SAF",
    "SV650AL7",
    "SV650AL8",
    "SV650AL9 / SV650XAL9",
    "SV650K/SV650SK",
    "SV650L7",
    "SV650L8",
    "SV650L9",
    "V-STROM 1000 ABS(DL1000AL8) / V-STROM 1000 XT ABS(DL100XAL8)",
    "V-STROM 1050",
    "V-STROM 1050XT",
    "V-STROM 650",
    "V-STROM 650XT",
    "V-STROM 650XT Adventure",
    "V-STROM 800",
    "V-STROM 800DE / V-STROM 800DE Adventure"
  ],
  "SYM": [
    "AE Series",
    "AJ Series",
    "AV Series",
    "AY Series",
    "BC Series",
    "CITYCOM",
    "CITYCOM 300I",
    "CITYCOM S 300I",
    "Citycom",
    "Cruisym",
    "DD50",
    "DS",
    "Duke 125",
    "FIDDLE",
    "FIDDLE II / LANCE CALI CLASSIC/LANCE HAVANA CLASSIC/LANCE PCH/LANCE CABO 125",
    "FIDDLE III 200I/ LANCE CALI CLASSIC 200I/ LANCE HAVANA CLASSIC 200I/ LANCE PCH 200I/ LANCE CABO 200I",
    "FS Series",
    "HD200",
    "JET",
    "JET 50",
    "LANCE CALI CLASSIC/LANCE HAVANA CLASSIC/LANCE PCH/LANCE CABO 150",
    "LANCE CALI CLASSIC/LANCE HAVANA CLASSIC/LANCE PCH/LANCE CABO/LANCE SOHO 50",
    "LL Series",
    "MIO",
    "MIO 50",
    "PF Series",
    "RV 200",
    "SANYANG",
    "SYMBA",
    "T2 250I (SYMFIGHTER)",
    "WOLF CLASSIC 150",
    "XA Series"
  ],
  "TAIWAN GOLDEN BEE": [
    "FCB"
  ],
  "Taiwan Golden Bee": [
    "TGB R50X"
  ],
  "Togo": [
    "Maxi 125",
    "Maxi 50",
    "T10",
    "T11",
    "T12",
    "T3",
    "T4"
  ],
  "Tomos": [
    "APN 4",
    "ATX 50 C",
    "CTX 80"
  ],
  "Triumph": [
    "Adventurer",
    "America",
    "Bobber TFC",
    "Bonneville",
    "Daytona",
    "Daytona 660",
    "Daytona 675 R",
    "De Luxe 6 S",
    "Explorer",
    "Legend",
    "Rocket 3",
    "Rocket 3 Storm",
    "Rocket III",
    "Scrambler",
    "Slippery Sam",
    "Speed",
    "Speed Four",
    "Speed Triple",
    "Speed Twin",
    "Speedmaster",
    "Sprint",
    "Street Cup",
    "Street Scrambler",
    "Street Triple",
    "Street Twin",
    "TF250",
    "TF450",
    "Thruxton",
    "Thunderbird",
    "Tiger",
    "Tiger Sport",
    "TR5MX",
    "TR7",
    "TR8",
    "Tracker",
    "Trident",
    "Trophy",
    "TT600"
  ],
  "Trojan": [
    "Trobike"
  ],
  "Tulamashzavod": [
    "Muravey"
  ],
  "TVS": [
    "Apache RTR 310"
  ],
  "Ultraviolette Automotive": [
    "Ultraviolette Tesseract"
  ],
  "Ural": [
    "Retro",
    "Tourist, Patrol, Gear Up",
    "Wolf"
  ],
  "Vectrix": [
    "VX-1",
    "VX-2"
  ],
  "Velocette": [
    "LE",
    "Thruxton",
    "Venom",
    "Viper"
  ],
  "Vespa": [
    "946",
    "Elettrica",
    "GTS",
    "GTS / GTV",
    "GTS RST / SEI GIORNI",
    "PRIMAVERA/SPRINT Elettrica",
    "Primavera / Sprint 150",
    "Primavera / Sprint 50",
    "Primavera Elettrica",
    "Vespino"
  ],
  "VinFast": [
    "Evo",
    "Feliz",
    "Impes",
    "Klara",
    "Klara S",
    "Tempest",
    "Theon",
    "Vento"
  ],
  "Voge": [
    "300 Rally",
    "300R",
    "300RR",
    "525ACX",
    "525DSX",
    "650DSX",
    "900DSX"
  ],
  "Walter vehicles": [
    "Walter M 922"
  ],
  "Wild Bill Gelbke": [
    "Auto Four",
    "Roadog"
  ],
  "Yadea": [
    "G5"
  ],
  "Yamaha": [
    "Bobby",
    "Bolt",
    "CZD300-A (XMAX 300)",
    "Fino",
    "FJR1300",
    "FZ250 Phazer",
    "FZ750",
    "FZR",
    "FZR1000",
    "FZR400",
    "FZS600 Fazer",
    "Mate",
    "Mio",
    "MT-10",
    "MTM690 (XSR700)",
    "MTM850 (XSR900)",
    "MTM890 (XSR900)",
    "MTN1000 (MT-10)",
    "MTN320 (MT-03)",
    "MTN690 (MT-07)",
    "MTN850 (MT-09)",
    "MTN890 (MT-09)",
    "MTT850 (tracer 900)",
    "MTT890 (tracer 9)",
    "MTT9 (tracer 900)",
    "Neos",
    "Nouvo",
    "Passol",
    "Popgal",
    "R1-Z",
    "RD500LC",
    "SRV",
    "SZR660",
    "TDM",
    "Ténéré",
    "Tricker",
    "TZR",
    "Vity",
    "Xenter",
    "Xeon",
    "XMAX",
    "XP500 / TMAX",
    "XS",
    "XT1200Z Super Tenere",
    "XT125X",
    "XTZ690 (tenere 700)",
    "XV1100 (virago 1100)",
    "XV250 (virago 250)",
    "XV535 (virago 535)",
    "XV750 (virago 750)",
    "XV920 (virago 920)",
    "XVS950 Bolt",
    "XZ 550",
    "YZF-R1",
    "YZF-R125",
    "YZF-R1M",
    "YZF-R3",
    "YZF-R6",
    "YZF-R7",
    "YZF-R7 (2022)",
    "YZF-R9",
    "YZF1000R Thunderace",
    "YZF600",
    "YZF600R",
    "YZF690",
    "YZF750",
    "YZR 250",
    "YZR 500",
    "YZR-M1",
    "Zippy"
  ],
  "Zündapp": [
    "Bella"
  ]
};

export const importedCatalogMeta = {
  "source": "Wikidata archive + NHTSA motorcycle makes/models + manual Turkey fallbacks",
  "syncedAt": "2026-04-08T13:25:49.731Z",
  "brandCount": 109,
  "modelCount": 1915
} as const;
